### ISSUE TITLE
There is a suspected memory leak in Amazon Linux.

### ISSUE THREAD

**Issue by woowadragonchan** [sipwise/rtpengine#1120]
Hi. I am using RTP-Engine with OpenSIPS to play media in phone service.
After a few months, I looked at the system indicators and found a suspected memory leak.

**Version** : 7.4.0.0
**Commit** : https://github.com/sipwise/rtpengine/tree/5acbf1ec87bfdd5b685fd4ac929997e191f90a9e

As shown in the figure below, every time a call is executed, the RSS of the memory increases.
<img width="1702" alt="rtpengine_rss" src="https://user-images.githubusercontent.com/44791087/100320979-5b51f680-3005-11eb-9e9c-9bf15a84981d.png">

Memory usage may vary for each service, but it is increasing by about 3% when looking at the monthly usage of memory used in our service. This number increases by about 0.1% per day.
<img width="453" alt="rtpengine_graph" src="https://user-images.githubusercontent.com/44791087/100321631-53468680-3006-11eb-8126-8609cb344ceb.png">

To verify this, I ran the valgrind test.
<img width="998" alt="valgrind_leak_summary" src="https://user-images.githubusercontent.com/44791087/100322594-da482e80-3007-11eb-811b-4311a4c71ba2.png">
<img width="1372" alt="valgrind_detail" src="https://user-images.githubusercontent.com/44791087/100322610-e03e0f80-3007-11eb-8350-4e896c64c8e9.png">

As a result of valgrind testing, it was found that there was a problem with the memory allocation part of the glib library.

Is this a false positive for valgrind?
If not, is there really a problem with the glib library in the current version of rtpengine?
If there is a problem, is there a problem with the current version of rtpengine and I need to upgrade it?
Or should it be viewed as normal memory consumption?

I am really curious.

**Comment by rfuchs** [comment]
It's a little bit of both.

To properly debug memory allocation with valgrind, you need to run rtpengine with the environment variable `G_SLICE=always-malloc` set. Otherwise you will get unreliable results.

The leak block you posted is from `config_load` which is executed exactly once at startup. So it isn't a "real" memory leak in the sense that it keeps consuming memory during runtime. It is however still fixed in later versions to make debugging easier (somewhere around commits 39b04ece or 08fc2eca3).

There also also some other single-allocation memory blocks that glib intentionally leaks.

When looking for memory leaks under valgrind, I suggest to let it run for a while and put a fair number of calls (not just one or two) and a good load on it. Then look in the leak report for whatever has the highest number of "blocks" and start from there.

**Comment by rfuchs** [comment]
Also, before you start looking for leaks in the version you have, I suggest you update at least to the latest commit in the mr7.5 branch.

**Comment by woowadragonchan** [comment]
Hi.
Thank you for your response.

I ran it again with the latest version of the mr7.5 branch, and the memory rise is still happening.

<img width="845" alt="first_ps" src="https://user-images.githubusercontent.com/44791087/100363823-9cb3c780-3040-11eb-9f57-456aa4e382a2.png">
<img width="845" alt="second_ps" src="https://user-images.githubusercontent.com/44791087/100363828-9faeb800-3040-11eb-9b88-57eaf7fe41f7.png">
<img width="846" alt="third_ps" src="https://user-images.githubusercontent.com/44791087/100363832-a2111200-3040-11eb-8543-a731df0a32cd.png">



And, out of the 7 leak blocks posted previously, 6 are occurring in config_load, and 1 is occurring in other parts. Is this also related to G_SLICE=... option?
<img width="504" alt="스크린샷 2020-11-26 오후 11 43 50" src="https://user-images.githubusercontent.com/44791087/100364981-2f089b00-3042-11eb-9962-d7585fce0070.png">

**Comment by rfuchs** [comment]
Anything you see that involves g_slice* is unreliable if you didn't have `G_SLICE=always-malloc` set

**Comment by woowadragonchan** [comment]
This is the result of valgrind test with g_slice option.
`G_SLICE=always-malloc valgrind --leak-check=full ./rtpengine --config-file=......`

There is definitely lost occurring in more blocks, and the g_malloc function is still visible.

<img width="652" alt="1" src="https://user-images.githubusercontent.com/44791087/100367783-15695280-3046-11eb-91cf-bdd59999fd1b.png">
<img width="691" alt="2" src="https://user-images.githubusercontent.com/44791087/100367798-19957000-3046-11eb-8111-d1ca545361ad.png">
<img width="494" alt="3" src="https://user-images.githubusercontent.com/44791087/100367801-1a2e0680-3046-11eb-8778-7a198ff7968b.png">

**Comment by rfuchs** [comment]
These are still all related to the config loading (except the thread_detach one) and not real runtime memory leaks. Also they're still fixed in later versions.

**Comment by woowadragonchan** [comment]
Okay.. I understood that these are all related to configuration loading and not real runtime memory leaks.
Assuming that the valgrind test is unreliable data,
Why is the memory rising regardless of the valgrind test?
While testing one call at a time (media playback), I am looking at the RSS of the memory, and it comes out as follows.

`process status`
<img width="827" alt="스크린샷 2020-11-27 오전 10 20 28" src="https://user-images.githubusercontent.com/44791087/100401304-8176a580-309c-11eb-8fa0-781ba6107c5f.png">

Memory RSS value increased from 13176 to 13288 to 13548.

Can the memory consumption caused by playing media be considered normal?
Or is it a bug?

**Comment by woowadragonchan** [comment]
Also, I ran valgrind to find a memory leak and put a significant number of calls (not just once or twice) and loads, but I still only get results related to g_malloc and no other memory leaks.

**Comment by rfuchs** [comment]
Real leaks would still show up with malloc or g_malloc in the call chain, so don't disregard those. If you had a large number of calls on rtpengine (AND you made sure all calls were fully closed before you shut it down), look for leak reports with "X bytes in Y blocks" with a high number Y. In particular the number Y is expected to rise proportionally with the number of calls you had on rtpengine.

**Comment by woowadragonchan** [comment]
I did two tests with valrgind.
The first call was made only once, and the second was 7 more call tests.
The results of `still-reachable` were different.
The second `still-reachable` value was larger than the first.

**First test. (1 call)**
<img width="571" alt="1" src="https://user-images.githubusercontent.com/44791087/100465918-71e67380-3113-11eb-96ff-6ebfdd1a160f.png">
**Second test. (7 calls)**
<img width="569" alt="2" src="https://user-images.githubusercontent.com/44791087/100465926-7448cd80-3113-11eb-8f28-855362c43812.png">

Looking at the log results for these two tests, it was confirmed that 7 more results were extracted as follows.

<img width="553" alt="calloc" src="https://user-images.githubusercontent.com/44791087/100466301-0e107a80-3114-11eb-9a43-bf0b151ceb11.png">

There seems to be a memory leak for the following stack, what's wrong with it?

**Comment by rfuchs** [comment]
This is the cookie cache. It's used to store and detect duplicate messages from the UDP and NG control protocols. It's cleaned up automatically as messages are received (once an hour I believe). Not a leak.

**Comment by woowadragonchan** [comment]
go through that routine every time play media?

**Comment by woowadragonchan** [comment]
Where do you control the cookie cache end time? Are there any options that can be controlled in the configuration file?

**Comment by woowadragonchan** [comment]
Looking at the valgrind manual it says that the still-reachable option means the program is probably fine. As you said, if the issue is a buffer for the cookie cache, and a buffer that will end after an hour, is it okay to see it as normal memory consumption without problems?

**Comment by rfuchs** [comment]
Yes absolutely. You will always see a memory increase immediately after (re)starting the daemon once you put calls on it. Not just from the cookie cache but also from other objects that have a slow start. But it should level off and not increase any more after running for a while.

**Comment by woowadragonchan** [comment]
Yes. I know that the memory rises once when the daemon starts up.

But, the symptom that is currently appearing is that you want to know whether it is a problem or not that the memory gradually increases every time you make a call test (rtpengine call).

So what I'm curious about is, is the cookie cache buffer you mentioned being allocated only once when the daemon starts???
Or is it assigned every time I do a call test(play media)?

**Comment by rfuchs** [comment]
The main structure is allocated on startup. Then for every request handled, the cookie and the response is stored within in. Then after 1-2 hours, it starts to get recycled.

**Comment by woowadragonchan** [comment]
Okay, I understood that for every request processed, a cookie is saved and cleaned up after a 1-2 hour.
In the service, the speed of traffic entering will be faster than the time when the cookie is cleared after 1-2 hours. If that happens, it seems that it is normal memory consumption that cookies that are not cleaned up (cleaned up after 1-2 hours) keep accumulating.
Okay, thank you for your kind response.

**Comment by woowadragonchan** [comment]
I re-inquire about the memory rise issue.
Version: lastest (`mr9.2`)

After testing several calls through a load test, memory is not returned even if you wait for more than 1 to 2 hours without entering traffic.
So I don't understand that memory keeps accumulating.

In my opinion, if I block the following functions related to media playback, the memory rise does not occur. (Of course it doesn't play either.)
Is there a problem with the thread for playing media?
Is it normal memory consumption?

Corresponding function.
path: `/daemon/media_player.c`
function: `avformat_find_stream_info(mp->fmtctx, NULL);`
function: `mp->handler->func(mp->handler, &packet);`

**Comment by rfuchs** [comment]
If I already knew that there was a problem in the code, I would have fixed it already.

If you think there's a memory leak somewhere, run it through valgrind and see what it says.

**Comment by rfuchs** [comment]
Cleaning up old tickets
